# Setup
title:        turndn profile page
tagline:      
baseurl:      ""
paginate:     5
permalink:    /:categories/:title.html

# About/contact
author:
  name:       turndn
  url:        https://turndn.github.io

# Gems
gems:
  - jekyll-paginate

exclude:
  - jekyll-cayman-theme.gemspec
  - README.md
  - Gemfile
  - Gemfile.lock


#Others
markdown: kramdown